import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/Toaster";
import SwapProvider from "@/components/SwapProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SwapProvider>
          <div className="mx-auto min-h-screen bg-[#FFC882] relative overflow-hidden">
            {children}
            <Footer />
            <Toaster />
          </div>
        </SwapProvider>
      </body>
    </html>
  );
}
